Fix build with gcc 10
A few symbols are defined in both ddrcheck.c and dgmodul4.c, causing the
link to fail with gcc 10. Fix this with externs, only referencing the
symbols from dgmodul4.c.

This fixes the following link-time errors (paths have been edited):

  aarch64-linux-gnu-ld: AArch64_obj/dgmodul4.o:dgmodul4.c:60: multiple definition of `gSubTrueData'; AArch64_obj/ddrcheck.o:ddrcheck.c:44: first defined here
  aarch64-linux-gnu-ld: AArch64_obj/dgmodul4.o:dgmodul4.c:59: multiple definition of `gSubErrData'; AArch64_obj/ddrcheck.o:ddrcheck.c:43: first defined here
  aarch64-linux-gnu-ld: AArch64_obj/dgmodul4.o:dgmodul4.c:58: multiple definition of `gSubErrAdd'; AArch64_obj/ddrcheck.o:ddrcheck.c:42: first defined here
  aarch64-linux-gnu-ld: AArch64_obj/dgmodul4.o:dgmodul4.c:57: multiple definition of `gTrueDdrData'; AArch64_obj/ddrcheck.o:ddrcheck.c:41: first defined here
  aarch64-linux-gnu-ld: AArch64_obj/dgmodul4.o:dgmodul4.c:57: multiple definition of `gErrDdrData'; AArch64_obj/ddrcheck.o:ddrcheck.c:41: first defined here
  aarch64-linux-gnu-ld: AArch64_obj/dgmodul4.o:dgmodul4.c:56: multiple definition of `gErrDdrAdd'; AArch64_obj/ddrcheck.o:ddrcheck.c:40: first defined here

Signed-off-by: Vincent Stehlé <vincent.stehle@arm.com>